#!/bin/bash

## uncompress files into ~/Downloads
## run ./install
## open /etc/pam.d/common-auth
## change line that says:
## auth    [success=1 default=ignore]      pam_unix.so nullok_secure
## to say:
## auth    [success=2 default=ignore]      pam_unix.so nullok_secure
## directly below, add this line:
## auth    [default=ignore]                pam_exec.so seteuid /usr/local/bin/gotcha
## take a break, you dun good

app=/usr/local/bin/
dir=/tmp/gotcha
zzz="sleep 2"

## installs required packages
echo "Acquiring some magic..."
## packages for sendEmail
sudo apt-get install libio-socket-ssl-perl libnet-ssleay-perl sendemail
## packages for ffmpeg, to interact with webcam
sudo apt-get install ffmpeg
echo "Magic acquired..."
$zzz

## makes install directories
echo "Making places for the stuff..."

if test -d "$dir"
then
        echo "Found directory...";
else
        echo "Directory not found..."
        $zzz
        echo "Creating directory $dir..."
        mkdir -p $dir;
fi
$zzz

## moves working directory to extracted dir
cd ~/Downloads/gotcha

##moves file to created directory
echo "Moving the stuff to the place..."
sudo cp gotcha $app
$zzz

## moves working directory to /usr/local/bin
cd $app

## makes script executable
echo "Making the stuff do a thing..."
sudo chmod +x gotcha
$zzz

echo "Finishing irrelevant dialog..."
$zzz
echo "Irrelevant dialog complete..."
$zzz
echo "Have a nice day :) "

